let verificar = document.querySelector('#botao').addEventListener('click', function() {
    let exib = document.querySelector('#LocalExib')
    let anoNasc = document.querySelector('#nasc')
    let V_anoNasc = anoNasc.value
    // O código acima está pegando no HTML o valor inserido no input:Number
    
    // Agora preciso descubrir um jeito de capturar se o user é do sexo masculino ou feminino.
})